version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BancoLucas
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ../
      dockerfile: CRUD/WebAPI/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BancoLucas;User=root;Password=root;

volumes:
  db_data:
